In [1]:
import sys

import os
import numpy as np

import pandas as pd
import os
import torch

# import warnings

from data_provider.GreenEnergyDataset import GreenEnergyDataSet
from utils.weights import compute_weights


In [2]:
torch.__version__

'2.1.0+cu121'

In [3]:
torch.cuda.is_available()

True

In [1]:
dataset  = GreenEnergyDataSet("datasets",flag="train",size=[96,48,96],external_var=[])
print(len(dataset))

NameError: name 'GreenEnergyDataSet' is not defined

In [3]:
weights = compute_weights(dataset.data_y,dataset.seq_len,dataset.pred_len)
np.save(f"weights_{dataset.seq_len}_{dataset.seq_len}_{dataset.pred_len}",weights)
print(weights.shape)
# print(a[1])

35064


d:\Urban\Assignemnt-3\weights.py:45: IntegrationWarning: The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.
  value,_ = quad(lambda x: gaussian_kernel(x,x_0,sigma) *np.interp(x, bins[j][:-1], emperical_densities[j]),a=mini,b=maxi)


(34872, 7)


[[0.00521574 0.00966874 0.0058293  ... 0.00850332 0.00359431 0.01005817]
 [0.00523732 0.00952617 0.00580337 ... 0.00848534 0.00469112 0.01005689]
 [0.00525772 0.00935548 0.00574107 ... 0.00840881 0.00587523 0.01005368]
 ...
 [0.00554964 0.0065565  0.00820148 ... 0.01030852 0.02182538 0.00452208]
 [0.00554941 0.00637872 0.00819996 ... 0.01027356 0.02224094 0.00462844]
 [0.00554891 0.00620305 0.0081966  ... 0.01020389 0.02265794 0.00465791]]


In [ ]:
import matplotlib.pyplot as plt
x=  np.array(a.LDs)
print(x)
for i in range(6):
    t = x[:,i]
    plt.plot(t)
    plt.show()


AttributeError: 'MyDataSet' object has no attribute 'LDs'